USE [InventoryManagement]

CREATE TABLE [ProductCategory]
(
	ID BIGINT NOT NULL PRIMARY KEY IDENTITY(101,1),
	CategoryName VARCHAR(200) NOT NULL,
	[Description] VARCHAR(500),
	IsActive BIT NOT NULL DEFAULT 1,
	CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
	ModifiedDate DATETIME NOT NULL DEFAULT GETDATE(),
	CreatedBy VARCHAR(100),
	ModifiedBy VARCHAR(100)
)

CREATE TABLE [ProductSubCategory]
(
	ID BIGINT NOT NULL PRIMARY KEY IDENTITY(101,1),
	SubCategory VARCHAR(200) NOT NULL,
	[Description] VARCHAR(500),
	CategoryID BIGINT FOREIGN KEY REFERENCES ProductCategory(ID) NOT NULL,
	IsActive BIT NOT NULL DEFAULT 1,
	CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
	ModifiedDate DATETIME NOT NULL DEFAULT GETDATE(),
	CreatedBy VARCHAR(100),
	ModifiedBy VARCHAR(100)
)
CREATE TABLE [Vendors]
(
	ID BIGINT NOT NULL PRIMARY KEY IDENTITY(101,1),
	VendorCode VARCHAR(100) NOT NULL,
	[Name] VARCHAR(200) NOT NULL,
	[Address] VARCHAR(500),

	IsActive BIT NOT NULL DEFAULT 1,
	CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
	ModifiedDate DATETIME NOT NULL DEFAULT GETDATE(),
	CreatedBy VARCHAR(100),
	ModifiedBy VARCHAR(100)
)

CREATE TABLE [VendorBranches]
(
	ID BIGINT NOT NULL PRIMARY KEY IDENTITY(101,1),
	BranchName VARCHAR(100) NOT NULL,
	[Address] VARCHAR(500),
	VendorID BIGINT FOREIGN KEY REFERENCES Vendors(ID) NOT NULL,
	IsHeadQuarter BIT NOT NULL DEFAULT 0,
	
	IsActive BIT NOT NULL DEFAULT 1,
	CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
	ModifiedDate DATETIME NOT NULL DEFAULT GETDATE(),
	CreatedBy VARCHAR(100),
	ModifiedBy VARCHAR(100)
)

CREATE TABLE [VendorContacts]
(
	ID BIGINT NOT NULL PRIMARY KEY IDENTITY(101,1),
	ContactName VARCHAR(200) NOT NULL,
	VendorID BIGINT FOREIGN KEY REFERENCES Vendors(ID) NOT NULL,
	BranchID BIGINT FOREIGN KEY REFERENCES VendorBranches(ID) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Phone VARCHAR(20) NOT NULL,
	IsPrimary BIT NOT NULL DEFAULT 0,

	IsActive BIT NOT NULL DEFAULT 1,
	CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
	ModifiedDate DATETIME NOT NULL DEFAULT GETDATE(),
	CreatedBy VARCHAR(100),
	ModifiedBy VARCHAR(100)
)

CREATE TABLE [Product]
(
	ID BIGINT NOT NULL PRIMARY KEY IDENTITY(101,1),
	ProductName VARCHAR(1000) NOT NULL,
	[Description] VARCHAR(500),
	ProductCode VARCHAR(50) NOT NULL,
	CategoryID BIGINT FOREIGN KEY REFERENCES ProductCategory(ID) NOT NULL,
	SubCategoryID BIGINT FOREIGN KEY REFERENCES ProductSubCategory(ID) NOT NULL,
	QuantityInStock BIGINT NOT NULL DEFAULT 0,
	AverageBuyPrice DECIMAL(10,2) DEFAULT 0,
	SellPrice DECIMAL(10,2) NOT NULL,
	Discount DECIMAL(10,2),
	TaxPrice DECIMAL(10,2) NOT NULL DEFAULT 0,
	ReorderLevel  BIGINT NOT NULL DEFAULT 0,

	IsActive BIT NOT NULL DEFAULT 1,
	CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
	ModifiedDate DATETIME NOT NULL DEFAULT GETDATE(),
	CreatedBy VARCHAR(100),
	ModifiedBy VARCHAR(100)
)

CREATE TABLE [ContactUs]
(
	ID INT NOT NULL PRIMARY KEY IDENTITY(101,1),
	[Name] VARCHAR(250) NOT NULL,
	[Email] VARCHAR(50) NOT NULL,
	[Phone] VARCHAR(15) NULL,
	[Message] VARCHAR(max),

	IsActive BIT DEFAULT 1,
	CreatedDate DATETIME DEFAULT GETDATE(),
	ModifiedDate DATETIME DEFAULT GETDATE()
)
